<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_keluar_model extends CI_Model
{

    public $table = 'barang_keluar';
    public $id = 'id_barang_keluar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_all_keluar()
    {
        $this->db->order_by('id_barang_keluar', 'desc');
        return $this->db->get('barang_keluar')->result_array();
    }

    function add_keluar($params)
    {
        $this->db->insert('barang_keluar',$params);
        return $this->db->insert_id();
    }

    function get_barang($id_barang_keluar)
    {
        return $this->db->get_where('barang_keluar',array('id_barang_keluar'=>$id_barang_keluar))->row_array();
    }

    function update_barang($id_barang_keluar,$params)
    {
        $this->db->where('id_barang_keluar',$id_barang_keluar);
        return $this->db->update('barang_keluar',$params);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang_keluar', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
    $this->db->or_like('pegawai', $q);
    $this->db->or_like('bidang', $q);
    $this->db->or_like('tanggal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang_keluar', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
    $this->db->or_like('pegawai', $q);
    $this->db->or_like('bidang', $q);
    $this->db->or_like('tanggal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_keluar_model.php */
/* Location: ./application/models/Barang_keluar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-10 15:13:50 */
/* http://harviacode.com */